// Generated by CoffeeScript 1.7.1
(function() {
  var $, browserSync, build_path, gulp, src_path;

  gulp = require('gulp');

  $ = require('gulp-load-plugins')();

  browserSync = require('browser-sync');

  src_path = {
    scripts: 'app/scripts',
    styles: 'app/styles'
  };

  build_path = {
    scripts: 'build/scripts',
    styles: 'build/styles'
  };

  gulp.task('reload', function() {
    return browserSync.reload();
  });

  gulp.task('serve', function() {
    return browserSync({
      server: {
        baseDir: './app',
        directory: true,
        index: "index.html"
      }
    });
  });

  gulp.task('dev', ['serve'], function() {
    return gulp.watch(['app/*'], ['reload']);
  });

}).call(this);

//# sourceMappingURL=gulpfile.map
