// Generated by CoffeeScript 1.9.3
var $, browserSync, build_path, gulp, src_path, webpack, webpackConfig;

gulp = require('gulp');

webpack = require('webpack');

webpackConfig = require('./webpack.config.js');

$ = require('gulp-load-plugins')();

browserSync = require('browser-sync').create();

src_path = {
  html: 'app/**/*.html',
  scripts: 'app/scripts/**/*.jsx',
  styles: 'app/styles/**/*.css',
  bundles_css: 'app/bundles/**/*.css',
  bundles_js: 'app/bundles/**/*.js'
};

build_path = {
  html: 'build',
  scripts: 'build/scripts',
  styles: 'build/styles'
};

gulp.task('reload', function() {
  return browserSync.reload();
});

gulp.task('css', function() {
  return gulp.src(src_path.styles).pipe(browserSync.stream());
});

gulp.task('serve', function() {
  return browserSync.init({
    server: 'app',
    directory: true
  });
});

gulp.task('webpack', function() {
  return webpack(webpackConfig, function(err, stats) {
    return $.util.log(err);
  });
});

gulp.task('dev', ['webpack', 'serve'], function() {
  gulp.watch(src_path.styles, ['webpack']);
  gulp.watch(src_path.scripts, ['webpack']);
  gulp.watch(src_path.html, ['reload']);
  gulp.watch(src_path.bundles_js, ['reload']);
  return gulp.watch(src_path.bundles_css, ['css']);
});
